//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordSearchWS_Client.SearchServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://helenswebservice.com/webservice", ConfigurationName="SearchServiceReference.SearchServiceSoap")]
    public interface SearchServiceSoap {
        
        // CODEGEN: Generating message contract since element name sentence from namespace http://helenswebservice.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://helenswebservice.com/webservice/Search", ReplyAction="*")]
        WordSearchWS_Client.SearchServiceReference.SearchResponse Search(WordSearchWS_Client.SearchServiceReference.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helenswebservice.com/webservice/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<WordSearchWS_Client.SearchServiceReference.SearchResponse> SearchAsync(WordSearchWS_Client.SearchServiceReference.SearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://helenswebservice.com/webservice", Order=0)]
        public WordSearchWS_Client.SearchServiceReference.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(WordSearchWS_Client.SearchServiceReference.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://helenswebservice.com/webservice")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sentence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string serachKey;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string sentence, string serachKey) {
            this.sentence = sentence;
            this.serachKey = serachKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://helenswebservice.com/webservice", Order=0)]
        public WordSearchWS_Client.SearchServiceReference.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(WordSearchWS_Client.SearchServiceReference.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://helenswebservice.com/webservice")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(string SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchServiceSoapChannel : WordSearchWS_Client.SearchServiceReference.SearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceSoapClient : System.ServiceModel.ClientBase<WordSearchWS_Client.SearchServiceReference.SearchServiceSoap>, WordSearchWS_Client.SearchServiceReference.SearchServiceSoap {
        
        public SearchServiceSoapClient() {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WordSearchWS_Client.SearchServiceReference.SearchResponse WordSearchWS_Client.SearchServiceReference.SearchServiceSoap.Search(WordSearchWS_Client.SearchServiceReference.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public string Search(string sentence, string serachKey) {
            WordSearchWS_Client.SearchServiceReference.SearchRequest inValue = new WordSearchWS_Client.SearchServiceReference.SearchRequest();
            inValue.Body = new WordSearchWS_Client.SearchServiceReference.SearchRequestBody();
            inValue.Body.sentence = sentence;
            inValue.Body.serachKey = serachKey;
            WordSearchWS_Client.SearchServiceReference.SearchResponse retVal = ((WordSearchWS_Client.SearchServiceReference.SearchServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WordSearchWS_Client.SearchServiceReference.SearchResponse> WordSearchWS_Client.SearchServiceReference.SearchServiceSoap.SearchAsync(WordSearchWS_Client.SearchServiceReference.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<WordSearchWS_Client.SearchServiceReference.SearchResponse> SearchAsync(string sentence, string serachKey) {
            WordSearchWS_Client.SearchServiceReference.SearchRequest inValue = new WordSearchWS_Client.SearchServiceReference.SearchRequest();
            inValue.Body = new WordSearchWS_Client.SearchServiceReference.SearchRequestBody();
            inValue.Body.sentence = sentence;
            inValue.Body.serachKey = serachKey;
            return ((WordSearchWS_Client.SearchServiceReference.SearchServiceSoap)(this)).SearchAsync(inValue);
        }
    }
}
